# Site settings
title: Nikolaos Efstratiou
description: Full Stack Developer Project Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nikolaos Efstratiou
user_description: Full-stack software developer with a passion for building scalable web applications. Proficient in front-end and back-end technologies, with experience in databases, APIs, and cloud deployment. Constantly learning and refining skills to create efficient, user-friendly solutions
user_title: Full Stack Developer
email: nikolaosefstr@gmail.com
# twitter_username: lorem_ipsum
github_username:  Nikos-efstratiou
gplus_username:  Nikolaos Efstratiou

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
