# Site settings
title: Nikolaos Efstratiou
description: Full Stack Developer Project Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nikolaos Efstratiou
user_description: Hi, I'm Nikolaos Efstratiou, an aspiring full-stack developer with a passion for creating dynamic and user-friendly web applications. I'm continuously learning and building my skills in both front-end and back-end technologies. I enjoy tackling new challenges and working on projects that bring ideas to life. My goal is to create seamless and intuitive digital experiences while growing as a developer. Join me on my journey as I explore the exciting world of development!
user_title: Full Stack Developer
email: nikolaosefstr@gmail.com
# twitter_username: lorem_ipsum
github_username:  Nikos-efstratiou
gplus_username:  Nikolaos Efstratiou

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
